
//------------------------ Inicio User --------------
// Busca user 
GET http://localhost:3000/users

### 
// Busca user por id
GET http://localhost:3000/users/:id
    
### 
// Cria user 
POST http://localhost:3000/users
Content-Type: application/json

###
// Atualiza user por id 
PUT http://localhost:3000/users/:id
Content-Type: application/json

###
// Atualiza senha do user por id 
PUT http://localhost:3000/users/senha/:id
Content-Type: application/json

###
// Deleta user por id 
DELETE  http://localhost:3000/users/:id


//------------------------ Inicio User Login --------------
### 
// Login do user 
POST http://localhost:3000/userslogin
Content-Type: application/json

//------------------------ Inicio Instituições --------------
### 
//Busca instituição
GET HTTP/1.1 http://localhost:3000/institutions

###
//Busca instituição por id
GET http://localhost:3000/institutions/:id

###
//Atualiza instituição por id
PUT http://localhost:3000/institutions/:id
Content-Type: application/json

###
//Deleta instituição por id
DELETE http://localhost:3000/institutions/:id


//------------------------ Inicio Projects --------------
### 
//Busca projetos
GET http://localhost:3000/projects

###
//Busca projetos por nome
GET http://localhost:3000/projects/:project_name

###
//Busca projetos por id
GET http://localhost:3000/projects/:id

###
// Cria projeto
POST http://localhost:3000/projects
Content-Type: application/json

###
// Atualiza projeto por id 
PUT http://localhost:3000/projects/:id
Content-Type: application/json

###
// Deleta projeto por id
DELETE  http://localhost:3000/projects/:id

//------------------------ Inicio Type Users --------------
### 
GET http://localhost:3000/type_users

//------------------------ Inicio Countries --------------

### 
GET http://localhost:3000/countries
