
//------------------------ Inicio User --------------
// Busca user 
GET http://localhost:3000/users

### 
// Busca user por id
GET http://localhost:3000/users/alun

### 
// Busca user por id
GET http://localhost:3000/users/:id
    
### 
// Busca user por instituição
GET http://localhost:3000/users/institution/:institution
### 
// Cria user 
POST http://localhost:3000/users
Content-Type: application/json

###
// Atualiza user por id 
PUT http://localhost:3000/users/:id
Content-Type: application/json

###
// Atualiza senha do user por id 
PUT http://localhost:3000/users/senha/:id
Content-Type: application/json

###
// Deleta user por id 
DELETE  http://localhost:3000/users/:id


//------------------------ Inicio User Login --------------
### 
// Login do user 
POST http://localhost:3000/userslogin
Content-Type: application/json

POST http://localhost:3000/userslogin/forgot-password
Content-Type: application/json

POST http://localhost:3000/userslogin/reset-password
Content-Type: application/json

//------------------------ Inicio Instituições --------------
### 
//Busca instituição
GET HTTP/1.1 http://localhost:3000/institutions

###
//Busca instituição por id
GET http://localhost:3000/institutions/:id

###
//Atualiza instituição por id
PUT http://localhost:3000/institutions/:id
Content-Type: application/json

###
//Deleta instituição por id
DELETE http://localhost:3000/institutions/:id


//------------------------ Inicio Projects --------------
### 
//Busca projetos
GET http://localhost:3000/projects

###
//Busca projetos por id
GET http://localhost:3000/projects/:id

###
// Cria projeto
POST http://localhost:3000/projects
Content-Type: application/json

###
// Atualiza projeto por id 
PUT http://localhost:3000/projects/:id
Content-Type: application/json

###
// Deleta projeto por id
DELETE  http://localhost:3000/projects/:id
//------------------------ Inicio Edital --------------

//Busca editais
GET http://localhost:3000/edital

###
//Busca editais por id
GET http://localhost:3000/edital/:id

###
// Cria edital
POST http://localhost:3000/edital
Content-Type: application/json

###
// Atualiza edital por id 
PUT http://localhost:3000/edital/:id
Content-Type: application/json

###
// Deleta edital por id
DELETE  http://localhost:3000/edital/:id
Content-Type: application/json   

//------------------------ Inicio Type Users --------------
### 
GET http://localhost:3000/type_users

//------------------------ Inicio Countries --------------

### 
GET http://localhost:3000/countries

###
//Busca pais por id
GET http://localhost:3000/countries/:id


//------------------------ Inicio Messages --------------

### 
POST  http://localhost:3000/messages/send
Content-Type: application/json

### 
POST  http://localhost:3000/messages/send-with-file
Content-Type: application/json

###
GET http://localhost:3000/messages/conversation/:user1/:user2

###
GET http://localhost:3000/messages/inbox/:userId


------------------------- Inicio Student Dashboard --------------


###
GET http://localhost:3000/student_dashboard/:id
Content-Type: application/json

//------------------------ Inicio Activities  --------------
###
GET http://localhost:3000/activities

###
GET http://localhost:3000/activities/user/:userId

###
GET http://localhost:3000/activities/created/:userId

###
GET http://localhost:3000/activities/:id



###
POST http://localhost:3000/activities
Content-Type: application/json

###
PUT http://localhost:3000/activities/:id
Content-Type: application/json

###
DELETE http://localhost:3000/activities/:id


